REM STAR plus - Spanish version - 13 PDFs
rem this PDF has 16 questions for change from TH to TD
rem create date Feb 22

REM SP-bexar 3 MCO 
"C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe" "C:\Users\jiang.shao\Dropbox (UFL)\MCO Report Card - 2024\Program\6. Graphics\TagEdit_refined\STAR+PLUS\MCO Report Cards 2024 - STAR+PLUS-ES - Bexar.pdf"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\3_MCO_TH.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_01_combine_h1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_02_rename_16_item.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_03_move_flag.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_04_combine_h2_h3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_05_combine_q1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_06_combine_q2.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_07_combine_q3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_08_combine_q4.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_09_combine_q5.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_10_combine_q6.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\close.exe"

timeout /t 2 /nobreak



rem sp-dallas 2 mco
"C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe" "C:\Users\jiang.shao\Dropbox (UFL)\MCO Report Card - 2024\Program\6. Graphics\TagEdit_refined\STAR+PLUS\MCO Report Cards 2024 - STAR+PLUS-ES - Dallas.pdf"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\2_MCO_TH.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_01_combine_h1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_02_rename_16_item.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_03_move_flag.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_04_combine_h2_h3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_05_combine_q1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_06_combine_q2.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_07_combine_q3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_08_combine_q4.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_09_combine_q5.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_10_combine_q6.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\close.exe"
timeout /t 2 /nobreak



rem sp-el paso 2 mco
"C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe" "C:\Users\jiang.shao\Dropbox (UFL)\MCO Report Card - 2024\Program\6. Graphics\TagEdit_refined\STAR+PLUS\MCO Report Cards 2024 - STAR+PLUS-ES - El Paso.pdf"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\2_MCO_TH.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_01_combine_h1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_02_rename_16_item.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_03_move_flag.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_04_combine_h2_h3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_05_combine_q1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_06_combine_q2.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_07_combine_q3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_08_combine_q4.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_09_combine_q5.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_10_combine_q6.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\close.exe"
timeout /t 2 /nobreak




rem sp-harris 3 mco
"C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe" "C:\Users\jiang.shao\Dropbox (UFL)\MCO Report Card - 2024\Program\6. Graphics\TagEdit_refined\STAR+PLUS\MCO Report Cards 2024 - STAR+PLUS-ES - Harris.pdf"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\3_MCO_TH.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_01_combine_h1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_02_rename_16_item.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_03_move_flag.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_04_combine_h2_h3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_05_combine_q1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_06_combine_q2.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_07_combine_q3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_08_combine_q4.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_09_combine_q5.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_10_combine_q6.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\close.exe"
timeout /t 2 /nobreak


rem sp-hidalo 2 mco
"C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe" "C:\Users\jiang.shao\Dropbox (UFL)\MCO Report Card - 2024\Program\6. Graphics\TagEdit_refined\STAR+PLUS\MCO Report Cards 2024 - STAR+PLUS-ES - Hidalgo.pdf"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\2_MCO_TH.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_01_combine_h1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_02_rename_16_item.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_03_move_flag.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_04_combine_h2_h3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_05_combine_q1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_06_combine_q2.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_07_combine_q3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_08_combine_q4.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_09_combine_q5.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_10_combine_q6.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\close.exe"

timeout /t 2 /nobreak


rem sp-jefferson 3 mco
"C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe" "C:\Users\jiang.shao\Dropbox (UFL)\MCO Report Card - 2024\Program\6. Graphics\TagEdit_refined\STAR+PLUS\MCO Report Cards 2024 - STAR+PLUS-ES - Jefferson.pdf"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\3_MCO_TH.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_01_combine_h1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_02_rename_16_item.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_03_move_flag.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_04_combine_h2_h3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_05_combine_q1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_06_combine_q2.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_07_combine_q3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_08_combine_q4.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_09_combine_q5.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_10_combine_q6.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\close.exe"

timeout /t 2 /nobreak


rem sp-lubbock 2 mco
"C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe" "C:\Users\jiang.shao\Dropbox (UFL)\MCO Report Card - 2024\Program\6. Graphics\TagEdit_refined\STAR+PLUS\MCO Report Cards 2024 - STAR+PLUS-ES - Lubbock.pdf"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\2_MCO_TH.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_01_combine_h1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_02_rename_16_item.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_03_move_flag.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_04_combine_h2_h3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_05_combine_q1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_06_combine_q2.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_07_combine_q3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_08_combine_q4.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_09_combine_q5.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_10_combine_q6.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\close.exe"

timeout /t 2 /nobreak


rem sp-MRSA central 2 mco
"C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe" "C:\Users\jiang.shao\Dropbox (UFL)\MCO Report Card - 2024\Program\6. Graphics\TagEdit_refined\STAR+PLUS\MCO Report Cards 2024 - STAR+PLUS-ES - MRSA Central.pdf"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\2_MCO_TH.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_01_combine_h1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_02_rename_16_item.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_03_move_flag.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_04_combine_h2_h3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_05_combine_q1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_06_combine_q2.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_07_combine_q3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_08_combine_q4.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_09_combine_q5.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_10_combine_q6.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\close.exe"

timeout /t 2 /nobreak


rem sp-MRSA northeast 2 mco
"C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe" "C:\Users\jiang.shao\Dropbox (UFL)\MCO Report Card - 2024\Program\6. Graphics\TagEdit_refined\STAR+PLUS\MCO Report Cards 2024 - STAR+PLUS-ES - MRSA Northeast.pdf"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\2_MCO_TH.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_01_combine_h1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_02_rename_16_item.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_03_move_flag.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_04_combine_h2_h3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_05_combine_q1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_06_combine_q2.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_07_combine_q3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_08_combine_q4.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_09_combine_q5.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_10_combine_q6.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\close.exe"

timeout /t 2 /nobreak


rem sp-MRSA west 2 mco
"C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe" "C:\Users\jiang.shao\Dropbox (UFL)\MCO Report Card - 2024\Program\6. Graphics\TagEdit_refined\STAR+PLUS\MCO Report Cards 2024 - STAR+PLUS-ES - MRSA West.pdf"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\2_MCO_TH.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_01_combine_h1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_02_rename_16_item.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_03_move_flag.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_04_combine_h2_h3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_05_combine_q1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_06_combine_q2.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_07_combine_q3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_08_combine_q4.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_09_combine_q5.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_10_combine_q6.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\close.exe"

timeout /t 2 /nobreak



rem sp-nueces 2 mco
"C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe" "C:\Users\jiang.shao\Dropbox (UFL)\MCO Report Card - 2024\Program\6. Graphics\TagEdit_refined\STAR+PLUS\MCO Report Cards 2024 - STAR+PLUS-ES - Nueces.pdf"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\2_MCO_TH.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_01_combine_h1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_02_rename_16_item.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_03_move_flag.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_04_combine_h2_h3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_05_combine_q1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_06_combine_q2.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_07_combine_q3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_08_combine_q4.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_09_combine_q5.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_10_combine_q6.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\close.exe"

timeout /t 2 /nobreak



rem sp-tarrant 2 mco
"C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe" "C:\Users\jiang.shao\Dropbox (UFL)\MCO Report Card - 2024\Program\6. Graphics\TagEdit_refined\STAR+PLUS\MCO Report Cards 2024 - STAR+PLUS-ES - Tarrant.pdf"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\2_MCO_TH.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_01_combine_h1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_02_rename_16_item.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_03_move_flag.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_04_combine_h2_h3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_05_combine_q1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_06_combine_q2.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_07_combine_q3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_08_combine_q4.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_09_combine_q5.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_10_combine_q6.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\close.exe"

timeout /t 2 /nobreak



rem sp-travis 2 mco
"C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe" "C:\Users\jiang.shao\Dropbox (UFL)\MCO Report Card - 2024\Program\6. Graphics\TagEdit_refined\STAR+PLUS\MCO Report Cards 2024 - STAR+PLUS-ES - Travis.pdf"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\2_MCO_TH.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_01_combine_h1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_02_rename_16_item.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_03_move_flag.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_04_combine_h2_h3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_05_combine_q1.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_06_combine_q2.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_07_combine_q3.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_08_combine_q4.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_09_combine_q5.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\save.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\sp_spa_10_combine_q6.exe"
"C:\Users\jiang.shao\Desktop\tiny_task_macro\sp_spa_macro\close.exe"

timeout /t 2 /nobreak
